In [3]:
import numpy as np

In [4]:
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
y = np.zeros((5,5))
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
z = np.empty((5,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
z.shape

(5, 5)

In [8]:
a = np.arange(1000000)

In [9]:
%time for i in range(1,10):r= [x * 2 for x in a]

Wall time: 4.55 s


In [10]:
%time for i in range(1,10):r= [a * 2]

Wall time: 67.9 ms


In [11]:
l = [1,4,5,7]

In [12]:
np.array(l)

array([1, 4, 5, 7])

In [13]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [14]:
x = np.zeros((10,10))

In [15]:
x.shape

(10, 10)

In [16]:
y =x.reshape((2,2,5,5))
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [17]:
x.dtype

dtype('float64')

In [18]:
y.ndim

4

In [19]:
z = np.random.randn((10))

In [20]:
z

array([-0.28246538, -0.47516507,  0.27794911, -0.67023482, -0.14583783,
       -0.90489138,  1.25763772, -0.33845166,  0.28975887, -0.77540214])

In [21]:
m = np.random.randn((10))
m

array([ 1.26838342e-03, -7.42377985e-01, -2.06998883e-01,  2.46613195e-01,
       -3.03890997e-01,  9.62884809e-01, -1.42435687e+00, -3.13971799e-01,
       -1.47635089e+00, -4.67938619e-01])

In [22]:
z + m

array([-0.281197  , -1.21754306,  0.07095023, -0.42362162, -0.44972882,
        0.05799343, -0.16671915, -0.65242346, -1.18659201, -1.24334076])

In [23]:
z - m

array([-0.28373376,  0.26721291,  0.48494799, -0.91684801,  0.15805317,
       -1.86777619,  2.68199458, -0.02447986,  1.76610976, -0.30746352])

In [24]:
z[z>0.1]

array([0.27794911, 1.25763772, 0.28975887])

In [25]:
h = np.ones((5,5))
h

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
h[1:-1,1:-1]=0

In [27]:
h

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
c = np.ones((10,10))
c

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
c[2:-2,2:-2]= 7

In [30]:
c

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 7., 7., 7., 7., 7., 7., 1., 1.],
       [1., 1., 7., 7., 7., 7., 7., 7., 1., 1.],
       [1., 1., 7., 7., 7., 7., 7., 7., 1., 1.],
       [1., 1., 7., 7., 7., 7., 7., 7., 1., 1.],
       [1., 1., 7., 7., 7., 7., 7., 7., 1., 1.],
       [1., 1., 7., 7., 7., 7., 7., 7., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [31]:
z[0]

-0.2824653801062157

In [32]:
v = np.random.randn(10,10)
v

array([[ 0.57014815, -0.49422813,  1.72588688, -0.07386788,  0.0587545 ,
         1.09255948,  0.77757288,  0.63410115,  1.50044499, -0.06286806],
       [ 0.14004458,  1.06253276, -0.45749964,  1.38009345, -0.14793114,
         0.94950004,  0.53225063, -1.21765683,  0.50849121, -3.39204343],
       [ 0.81526591, -1.59283505,  3.45490484, -0.745411  ,  0.96729316,
         0.80826401, -0.39798752,  0.37710928, -1.60115491,  0.71753583],
       [-1.77467015, -0.79750238,  0.80681071,  0.33400647, -2.05483883,
        -0.67279675,  0.34265856,  0.38878654,  0.02304232, -0.35163257],
       [-0.49670727,  1.10989207,  0.99130778, -2.25408219, -0.50606758,
        -0.49425465, -0.66427052, -0.6475084 ,  0.4853674 , -0.30758098],
       [-0.24461866,  0.03881175, -1.86296674,  0.95531827, -0.79602472,
        -0.31362604,  0.33056439,  1.28939999, -1.19717671, -0.3893418 ],
       [ 0.83820441,  2.28749819, -0.42286524,  1.08564936, -0.54197273,
        -0.96277041, -0.48075618,  0.92363089

In [33]:
v[0]

array([ 0.57014815, -0.49422813,  1.72588688, -0.07386788,  0.0587545 ,
        1.09255948,  0.77757288,  0.63410115,  1.50044499, -0.06286806])

In [34]:
v[0][4]

0.058754495564189206

In [35]:

v[1:10:2]

array([[ 0.14004458,  1.06253276, -0.45749964,  1.38009345, -0.14793114,
         0.94950004,  0.53225063, -1.21765683,  0.50849121, -3.39204343],
       [-1.77467015, -0.79750238,  0.80681071,  0.33400647, -2.05483883,
        -0.67279675,  0.34265856,  0.38878654,  0.02304232, -0.35163257],
       [-0.24461866,  0.03881175, -1.86296674,  0.95531827, -0.79602472,
        -0.31362604,  0.33056439,  1.28939999, -1.19717671, -0.3893418 ],
       [ 0.47875163, -1.24189474,  0.20310552,  1.11616091, -0.47168435,
        -1.09094613, -0.64457479,  0.39565468, -0.52703164,  0.19865043],
       [-1.81491746,  0.8732625 , -1.17995461, -1.78875594,  0.63702135,
         1.05556425, -1.0000257 ,  0.534927  , -0.66230126,  0.89224683]])

In [36]:
v[::,0:4]

array([[ 0.57014815, -0.49422813,  1.72588688, -0.07386788],
       [ 0.14004458,  1.06253276, -0.45749964,  1.38009345],
       [ 0.81526591, -1.59283505,  3.45490484, -0.745411  ],
       [-1.77467015, -0.79750238,  0.80681071,  0.33400647],
       [-0.49670727,  1.10989207,  0.99130778, -2.25408219],
       [-0.24461866,  0.03881175, -1.86296674,  0.95531827],
       [ 0.83820441,  2.28749819, -0.42286524,  1.08564936],
       [ 0.47875163, -1.24189474,  0.20310552,  1.11616091],
       [ 1.01276596, -1.67400968, -0.19170551, -1.23711927],
       [-1.81491746,  0.8732625 , -1.17995461, -1.78875594]])

In [37]:
v[0:4,::]

array([[ 0.57014815, -0.49422813,  1.72588688, -0.07386788,  0.0587545 ,
         1.09255948,  0.77757288,  0.63410115,  1.50044499, -0.06286806],
       [ 0.14004458,  1.06253276, -0.45749964,  1.38009345, -0.14793114,
         0.94950004,  0.53225063, -1.21765683,  0.50849121, -3.39204343],
       [ 0.81526591, -1.59283505,  3.45490484, -0.745411  ,  0.96729316,
         0.80826401, -0.39798752,  0.37710928, -1.60115491,  0.71753583],
       [-1.77467015, -0.79750238,  0.80681071,  0.33400647, -2.05483883,
        -0.67279675,  0.34265856,  0.38878654,  0.02304232, -0.35163257]])

In [38]:
j = np.array([10,9,8,4,1,2])

In [39]:
n = np.array([12,7,5,5,0,1])

In [40]:
np.maximum(j,n)

array([12,  9,  8,  5,  1,  2])

In [41]:
np.sqrt(j)

array([3.16227766, 3.        , 2.82842712, 2.        , 1.        ,
       1.41421356])

In [42]:
np.power(j,2)

array([100,  81,  64,  16,   1,   4], dtype=int32)

In [43]:
np.power(n,2)

array([144,  49,  25,  25,   0,   1], dtype=int32)

In [44]:
np.log(j)

array([2.30258509, 2.19722458, 2.07944154, 1.38629436, 0.        ,
       0.69314718])

In [45]:
np.floor(j)

array([10.,  9.,  8.,  4.,  1.,  2.])

In [46]:
np.floor(n)

array([12.,  7.,  5.,  5.,  0.,  1.])

In [47]:
np.modf(n)

(array([0., 0., 0., 0., 0., 0.]), array([12.,  7.,  5.,  5.,  0.,  1.]))

In [48]:
salary = np.array([0,-1,50000,100000])

In [49]:
np.where(salary <= 0, 25000,salary)

array([ 25000,  25000,  50000, 100000])

In [50]:
salary = np.array([0,-1,50000,100000])

In [51]:
np.where(salary <= 0, 'Not Ok','Ok')

array(['Not Ok', 'Not Ok', 'Ok', 'Ok'], dtype='<U6')

In [52]:
j = np.array([10,9,8,9,1,8])

In [53]:
j.mean()

7.5

In [54]:
j.cumsum()

array([10, 19, 27, 36, 37, 45], dtype=int32)

In [55]:
j.cumprod()

array([   10,    90,   720,  6480,  6480, 51840], dtype=int32)

In [56]:
np.unique(j)

array([ 1,  8,  9, 10])

In [57]:
np.sort(j)

array([ 1,  8,  8,  9,  9, 10])

In [58]:
d = j>7
d

array([ True,  True,  True,  True, False,  True])

In [59]:
d.sum()

5

In [60]:
d.any()

True

In [61]:
d.all()

False

In [108]:
j = np.array([10,9,8,9,1,8])
j

array([10,  9,  8,  9,  1,  8])

In [109]:
k = np.array([10,19,18,19,11,18])
k

array([10, 19, 18, 19, 11, 18])

In [110]:
np.save('testj',j)

In [111]:
np.load('testj.npy')

array([10,  9,  8,  9,  1,  8])

In [117]:
np.savez('testjk',j=j,k=k)

In [118]:
loadjk =np.load('testjk.npz')
loadjk

In [124]:
loadjk['k']

array([10, 19, 18, 19, 11, 18])

In [125]:
x = np.random.randn(3,2)
x

array([[ 0.23612293, -0.31478281],
       [ 0.67015929, -0.39551256],
       [-0.05778848, -0.21909175]])

In [128]:
y = np.random.randn(2,3)
y

array([[-0.40765832,  0.71693102,  1.12220818],
       [ 1.53892857,  0.70389721, -1.08219443]])

In [129]:
x.dot(y)

array([[-0.58068573, -0.05229089,  0.60563529],
       [-0.88186159,  0.20205779,  1.18007972],
       [-0.31360861, -0.19564843,  0.17224917]])

# Numpy

In [1]:
import numpy as np

# Creating Array

In [2]:
my_list = [1,2,3]
x = np.array(my_list)
x

array([1, 2, 3])

In [3]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [4]:
m = np.array([[7,8,9],[10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [5]:
n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [6]:
n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [11]:
o = np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [20]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [21]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.diag(x)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [26]:
np.array([1,2,3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [28]:
np.repeat([1,2,3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [23]:
p = np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [25]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Operations

In [40]:
x + y

array([5, 7, 9])

In [41]:
x * y

array([ 4, 10, 18])

In [42]:
x**2

array([1, 4, 9], dtype=int32)

In [43]:
x.dot(y)

32

In [45]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [47]:
z.shape

(2, 3)

In [48]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [49]:
z.T.shape

(3, 2)

In [50]:
z.dtype

dtype('int32')

In [53]:
z = z.astype('f')
z.dtype

dtype('float32')

In [26]:
a = np.array([-4,-2,1,3,5])
a

array([-4, -2,  1,  3,  5])

In [27]:
a.sum()

3

In [34]:
a.max()

5

In [36]:
a.min()

-4

In [37]:
a.mean()

0.6

In [38]:
a.std()

3.2619012860600183

In [39]:
a.argmax()

4

In [40]:
a.argmin()

0

# Indexing and Slicing

In [41]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [42]:
s[0], s[4], s[0:3]

(0, 16, array([0, 1, 4], dtype=int32))

In [43]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [44]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [45]:
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

In [46]:
a = np.arange(36)
a.resize(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [48]:
a[2,2]

14

In [49]:
a[3, 3:6]

array([21, 22, 23])

In [50]:
a[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [51]:
a[-1, ::2]

array([30, 32, 34])

In [52]:
a[a>30]

array([31, 32, 33, 34, 35])

In [54]:
a[a>30] = 30
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [57]:
r2 = a[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [59]:
r2[:]= 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [61]:
a

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [62]:
r_copy = a.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [63]:
r_copy[:]= 10
print(r_copy)
print()
print(a)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]
